TLDRAW_ASSETS_ALLOWED_MIME_TYPES_LIST : "image/png,image/jpeg,image/gif,image/svg+xml"
TLDRAW_LOG_LEVEL: "error"
TLDRAW_METRICS_COLLECT_DEFAULT: "true"
TLDRAW_ASSETS_ENABLED: "true"
TLDRAW_WEBSOCKET_PATH: "/tldraw-server"
NOT_AUTHENTICATED_REDIRECT_URL: "https://{{ DOMAIN }}/login"

TLDRAW_SERVER_MEMORY_LIMITS: "2Gi"
TLDRAW_SERVER_MEMORY_REQUESTS: "2Gi"
TLDRAW_SERVER_WORKER_MEMORY_LIMITS: "2Gi"
TLDRAW_SERVER_WORKER_MEMORY_REQUESTS: "150Mi"