# https://github.com/groundhog2k/helm-charts/blob/master/charts/valkey/RELEASENOTES.md
TLDRAW_VALKEY_CHART_VERSION: 2.2.1
TLDRAW_VALKEY_IMAGE_VERSION: 9.0.0
TLDRAW_VALKEY_REDIS_EXPORTER_IMAGE_VERSION: v1.80.0
TLDRAW_VALKEY_REPLICAS: 3
